### PR TITLE
WIOD 2016 and new format for WIOD2013

### PR DESCRIPTION
**Pull request by zauster**
Hey,

here are the functions that allow access to the new 2016 version of the WIOD.

Additionally, a new format for the tables of the WIOD 2013, as discussed in #2.
I also moved the package and data documentation in separate files.

Best,
Oliver

### CODE REVIEW

**Comment by bquast** [comment]
Hey, sorry just looking at this now. I was away for the weekend. Looks like a lot of work in this.

**Comment by bquast** [comment]
Ok, I am going to look at this in detail now, though I am sure it can be merged as is.

Only thought, from the updated examples, maybe we should update decompr so that it can simply take one iot object?

**Comment by zauster** [comment]
Sure, let's do that.

**Comment by bquast** [comment]
Ok, let me see if I can find a way to do this with backward compatibility

**Comment by bquast** [comment]
In any case, for that we will need to add the class to these objects. Something like:

    class(wiot_1995) <- 'iot'

**Comment by bquast** [comment]
we also might want to see if there is a way to load data.table silently

**Comment by bquast** [comment]
Ok, I did this:

https://github.com/bquast/decompr/commit/9f3bb50adc520f28f0bf19b52bd8412299782924

which seems to work. what do you think? we'd have to add `class(obj) <- 'iot'` to all objects.

**Comment by zauster** [comment]
I'll add the class attribute

**Comment by bquast** [comment]
thanks! lets leave this as is for a bit, ill try and clean up the rstudio addin for decompr and get everything on cran, then we can also update this one on cran

**Pull request merged**
